# CivicActions Ghost Example Compose
# Repo: https://github.com/BeltwayCloud/ca-ghost
# Demo of CA website ghost deployment
version: '3.1'

services:

  ghost:
    image: ghost:latest
    hostname: caghost
    restart: always
    ports:
      - 12368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      - database__client=mysql
      - database__connection__host=cadb
      - database__connection__user=root
      - database__connection__password
      - database__connection__database=ghost
      - url
      - mail__options__port=465
      - mail__from
      - mail__transport=SMTP
      - mail__options__auth__pass
      - mail__options__service=Gmail
      - server__port=2368
      - server__host=0.0.0.0
    volumes:
      - ca-ghost:/var/lib/ghost/content
    networks:
      - utilities

  db:
    image: mysql:8.0
    hostname: cadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ca-ghost-db:/var/lib/mysql
    networks:
      - utilities

volumes:
  ca-ghost:
  ca-ghost-db:

networks:
  utilities:
    external: true